import monstera from '../assets/monstera.png';

export const plantList = [
  {
    name: 'monstera',
    category: 'classique',
    id: '1ed',
    light: 2,
    water: 1,
    cover: monstera,
    price: 15,
  },

  {
    name: 'ficus lyrata',
    category: 'classique',
    id: '2ab',
    light: 3,
    water: 2,
    cover: monstera,
    price: 10,
  },
  {
    name: 'pothos argenté',
    category: 'classique',
    id: '3sd',
    isSpecialOffer: true,
    light: 2,
    water: 3,
    cover: monstera,
    price: 12,
  },
  {
    name: 'yucca',
    category: 'classique',
    id: '4kk',
    light: 3,
    water: 3,
    cover: monstera,
    price: 9,
  },
  {
    name: 'olivier',
    category: 'extérieur',
    id: '5pl',
    light: 1,
    water: 3,
    cover: monstera,
    price: 13,
  },
  {
    name: 'géranium',
    category: 'extérieur',
    id: '6uo',
    light: 2,
    water: 1,
    cover: monstera,
    price: 18,
  },
  {
    name: 'basilique',
    category: 'extérieur',
    id: '7ie',
    isSpecialOffer: true,
    light: 2,
    water: 2,
    cover: monstera,
    price: 11,
  },
  {
    name: 'aloe',
    category: 'plante grasse',
    id: '8fp',
    isSpecialOffer: true,
    light: 3,
    water: 1,
    cover: monstera,
    price: 16,
  },
  {
    name: 'succulente',
    category: 'plante grasse',
    id: '9vn',
    light: 1,
    water: 1,
    cover: monstera,
    price: 9,
  },
];
